version: 2

jobs:
  lint-dockerfile:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run hadolint
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
  test-app:
    docker:
      - image: golang:1.15-alpine
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push karsajobs
          command: sh build_push_image_karsajobs.sh

workflows:
  karsajobs:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs

