version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable

jobs:
  lint-dockerfile:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lint Dockerfile
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile

  test-app:
    docker:
      - image: golang:1.15-alpine
    steps:
      - checkout
      - run:
          name: Test app
          command: |
            apk update
            apk add gcc musl-dev
            go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push karsajobs app
          command: sh build_push_image_karsajobs.sh

workflows:
  version: 2
  karsajobs:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs:
          context: Github

