version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:2.12.0
    steps:
      - checkout
      - run: hadolint < Dockerfile
  test-app:
    docker:
      - image: golang:1.15-alpine
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    docker:
      - image: docker:dind
    steps:
      - checkout
      - run: bash build_push_image_karsajobs.sh

workflows:
  build_and_test:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs

